version: "3"
services:
  db:
    build:
      context: ./db
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context:
        ./app
    depends_on:
      - db
    environment:
      - DB_HOST=db
    container_name: python_app
    links:
      - db
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql